### PR TITLE
Update tests to force type. 

### PR DESCRIPTION
**Pull request by MadeByMike**
Should fix CI failures due to non-visible elements.

### CODE REVIEW

**Comment by MadeByMike** [comment]
No changeset required for this?

**Comment by timleslie** [comment]
Approved in principle, need to fix the typos to make it work. Also, give it a `yarn format` because the latest `.md` will get some changes which might as well come along for the ride.

**Comment by timleslie** [comment]
These projects don't get published so no need for a changeset.

**Comment by jesstelford** [comment]
force

**Pull request merged**
