### PR TITLE
constrain GraphiQL playground to GET requests only

### PR DESCRIPTION
**Pull request by dcousens**
(as title)

### CODE REVIEW

**Comment by jesstelford** [comment]
Needs prettier run over the file `yarn format:file packages/server/lib/graphql.js`

**Comment by dcousens** [comment]
@jesstelford done

**Comment by gautamsi** [comment]
No Reason to do this.

**Comment by dcousens** [comment]
@jesstelford I was trying something out,  I `POST`'d by mistake... and it returned a web page.
There is no reason **to** do that.

**Pull request merged**
