### PR TITLE
Add missing arch-ui deps to admin-ui

### PR DESCRIPTION
**Pull request by mitchellhamilton**
These dependencies were missing from the admin-ui package but preconstruct was covering up the fact that this would be broken when published. I found this when I was working on #993 because it's using a different version of preconstruct which doesn't cover up these problems.

I also didn't add a changeset since this package will already be released because of the changeset in #1023

### CODE REVIEW

**Comment by Noviny** [comment]
> I also didn't add a changeset since this package will already be released because of the changeset in #1023

I don't want to be the changeset police, but am wanting to understand the reasoning behind not having a changeset because something else will release it? I would generally still want a changeset, just so the change in this PR ('add missing dependencies') can be included in the changelog for the package.

**Comment by mitchellhamilton** [comment]
> I don't want to be the changeset police, but am wanting to understand the reasoning behind not having a changeset because something else will release it? I would generally still want a changeset, just so the change in this PR ('add missing dependencies') can be included in the changelog for the package.

1. I wanted to this quickly and I couldn't be bothered adding a changeset
2. I would argue something like this _shouldn't_ be in the changelog since the thing that it's fixing hasn't been released yet so it doesn't affect consumers. I don't really feel that strongly about this point though

**Comment by jossmac** [comment]
Hmm, #1023 was released before this...

**Comment by mitchellhamilton** [comment]
> Hmm, #1023 was released before this...

Huh? Do you mean it was merged before this? Because we haven't done a release since that PR.

**Comment by jossmac** [comment]
> Because we haven't done a release since that PR.

Okay cool. I assumed anything that went into master was released.

**Pull request merged**
