### PR TITLE
Better error message when no adapter is found (fixes #1628)

### LINKED ISSUE #1628: Update error message for missing adapter
```
      throw new Error('Need an adapter, yo');
```

Probably isn't the right tone of voice :-)

### PR DESCRIPTION
**Pull request by Vultraz**

### CODE REVIEW

**Comment by jesstelford** [comment]
Haha, that was a great placeholder! But it has clearly outlived the maturity of the project :P 

This PR didn't contain a Changeset when it was merged; we'll need to add a `patch` change @timleslie

**Comment by jesstelford** [comment]
@all-contribytors Can you add @Vultraz for code?

**Comment by timleslie** [comment]
Oh, I made an executive decision that this PR could live without a changeset since it's so trivial and the `keystone` package is already on track for a patch level release.

**Comment by jesstelford** [comment]
@all-contributors Can you add @Vultraz for code?

**Pull request merged**
