### PR TITLE
Expand create keystone app CLI

### PR DESCRIPTION
**Pull request by MadeByMike**
Updates the create-keystone-app cli.

1. Add the ability to create an app in an existing empty directory
1. Add the ability to select from available templates
1. Added the blank template

ks-create-prompt

### CODE REVIEW

**Comment by gautamsi** [comment]
I think the plan is to get away from template directory and use `create-next-app` like `--example` switch

**Comment by MadeByMike** [comment]
We can still do that. Is there an issue that describes how it would work? 

I don't think any future changes to create-keystone-app would need to block this. It can evolve :)

**Comment by mitchellhamilton** [comment]
IMO, we shouldn't add more templates like this, we should rip out the templates and make create-keystone-app essentially clone the projects from `demo-projects` since it will solve #1377 and mean we won't have to maintain even more projects.

**Comment by MadeByMike** [comment]
Generally I like the idea. Currently I don't think the demo projects are 100% what you'd want from a CLI but I think they could be aligned without too much work. I can't see someone wanting scaffold out the meetup demo as a starting point. It's really to specific. It works as a learning exercise but not so much a scaffolding project.

Having said that, I've talked with @jesstelford about the need for more a few more granular demos, for example maybe one with simple a detached React front-end that you'd deploy separately to your Keystone application. And maybe a Gatsby one as well as a few others.... what's most important here is good examples of how to structure these projects rather than the content. The current todo example is the opposite of this. To be fair warns people of this in the code and is a good into to lists etc.... Maybe it should be a pure JS example and not React.

On this note, it would also be nice if the CLI templates\demo guided not towards the desired application, ie, blog, todo, meetup, but towards the desired tech. Eg. Help me choose my stack, Mongo or Postgres + React, Next, Gatsby etc... often these are the decisions I have in mind when I start and don't mind if the example is bare bones (or virtually blank). I need just enough to show me how to work with it. I care more that webpack, babel and npm scripts etc... are configured for me.

Perhaps the end goal of the CLI does need more thought.

**Comment by mitchellhamilton** [comment]
Makes sense 👍 

The thing that I care about isn’t what projects that exist right now that we pull from, the thing I care about is not doing the templating stuff because it’s causing issues like that package manager thing and we can’t test the templates locally.

So I think the answer might be create a new directory for examples with tech stack things like you mentioned.

**Comment by MadeByMike** [comment]
Sounds good @mitchellhamilton. We could also selectively include some demos as options in the CLI. That would add a manual step to include it somehow but it's a tiny bit of work and never needs updating. 

The only challenge here is we're creating a dependency the demos repo and the CLI package. Is there any way to manage this so that editing the demos can't break the CLI. One solution I guess it to have a CI test for each of them?

**Comment by mitchellhamilton** [comment]
I think having a quick smoke test that starts the app should be fine but also, I don’t think next has tests like that and they work fine with all their examples.

**Comment by MadeByMike** [comment]
@mitchellhamilton I took your feedback onboard and once we land #1468 I've got some plans for a new method with the CLI I think you might like. Going to close this for now.

**Pull request closed without merging**
