### PR TITLE
Allow core field types that don't support all core DB adapters

### PR DESCRIPTION
**Pull request by molomby**
See #1335

### CODE REVIEW

**Comment by molomby** [comment]
> I'm concerned this change would open a path to where we break our promise of "just pick an adapter and KS5 will work!" - some subsets of types would only work in some subsets of database adapters.

This is a tricky one... On one hand I share you concern -- people should be able to pick up KS, pick an adapter and have everything work as they'd expect. On the other hand I think we need to be careful about oversimplifying things.

Different storage mechanisms have different abilities and different strengths. Not all adapters (even those in core) will or should support the same functionality.

Eg -- I think there should be a Mongo ObjectID field type. This would be useful if you wanted to reference an item in a different DB (so not a relationship field, just an ID). Could we support this on Knex? Absolutely. Should we bother? Well.. maybe, but I wouldn't want to block its release on that basis. 95% of the people who will want to use this type will be on the Mongoose adapter.

> This problem will only be exacerbated as we add more database adapters (eg; #1310)

Completely.. but do you really want to support many-to-many relationships on a JSON DB adapter? Or full text indexing with configurable languages on an in memory DB? It's doable, sure, but you risk building a stack of functionality no one actually wants. I'm 100% ok saying that, if you want branching full text search over a set of items, you need to pick a storage adapter that supports that functionality and, more to the point, _it's ok to build a new adapter that doesn't necessarily support that functionality_.

I'm worried that if we say "every core adapter must support every core field type/list config" is a hard rule we'll end up either:

* Creating a huge amount of work and holding back useful functionality until it supports all the everything, or..
* Be forced to reduce our core functionality to the lowest common denominator that all core adapter can support

> The linked issue mentions you want to create a new type that only supports Knex for now; can I suggest you do that as a separate package instead of as a core KS5 type? That way you don't run into any failing tests here, and can still use the type ASAP.

Yeah, I'm working on other branches that need this to be core. Specifically..

* I want ID columns to use existing field types and be added (automatically) to the field array, rather than being exceptional
* Devs should be able to specify the type used for the list ID

Happy to discuss all of this as well ^^

**Comment by molomby** [comment]
Interested to here @timleslie and @JedWatsons thoughts on this too ^^

**Comment by jesstelford** [comment]
> people should be able to pick up KS, pick an adapter and have everything work as they'd expect.

Yes, agreed. All core field types and core database adapters should _just work as expected_.

> Eg -- I think there should be a Mongo ObjectID field type. [..] Could we support this on Knex? Absolutely. Should we bother?

Yes.

If not, then it shouldn't be a core field type.

> do you really want to support many-to-many relationships on a JSON DB adapter?

Yes.

> full text indexing with configurable languages on an in memory DB?

No. This is not a feature of Keystone.

> it's ok to build a new adapter that doesn't necessarily support that functionality.

Agreed. That adapter can be a seperate package, and is not a core adapter.

> I'm worried that [..] holding back useful functionality until it supports all the everything

Until it classifies as a core field type, it can still be a perfectly usable third party field type. Publishing npm modules is cheap, and if it fully qualifies for inclusion in core, then we can bring it in 👍

> - I want ID columns to use existing field types and be added (automatically) to the field array, rather than being exceptional
> - Devs should be able to specify the type used for the list ID

Can you open an issue for this functionality? There is ongoing work that will make this much easier (specifically; de-special-casing the `label` field in a similar way).

**Comment by molomby** [comment]
Aaah ok, so we're actually talking about the definition of "core". I'd aways though the core Keystone field types and adapters should be designed and tested to work well together but wouldn't have said "all core field types work with all core adapters" was a _hard_ rule. 

Spoke to @JedWatson about this all last night and he's a lot closer to your interpretation. He reckons the `Uuid` field should be core but also should support Mongoose as a priority (even if it does so in a crappy way). I still tend to think a small number of well justified, short-term exceptions is better than a half baked implementation (but not strongly).

There's also talk of building out `Increment` (ie. an auto-incrementing serial value) and `MongoID` field types that would exist in the monorepo but outside the core fields package.

> Can you open an issue for this functionality? There is ongoing work that will make this much easier (specifically; de-special-casing the label field in a similar way).

Nice one. Yeah, I'll be back on this tomorrow (2019-06-28); let's catch up then? Would be great to hash some of these other aspects/field types out.

**Pull request closed without merging**
