### PR TITLE
Remove dupplicate mongodb-memory-server

### PR DESCRIPTION
**Pull request by VinayaSathyanarayana**
Remove mongodb-memory-server from dev dependencies (It is already present in dependencies)

### CODE REVIEW

**Comment by timleslie** [comment]
Hi @VinayaSathyanarayana, thanks for the PR. Could I ask you to mark your repo as `public`, that way our CI will be able to run against your PRs, which will make it easier for us to merge them in. Thanks! 👍

**Comment by VinayaSathyanarayana** [comment]
Done. Thanks for the feedback. Made the repo public

**Comment by mitchellhamilton** [comment]
@VinayaSathyanarayana could you enable the "Allow edits from maintainers. " option in this PR so that we can merge master into this branch and then merge it into master? (it's below the participants thing on the right)

**Comment by VinayaSathyanarayana** [comment]
Done - Allow edits from maintainers is turned ON (Ticked ON)

**Comment by timleslie** [comment]
Hmm, it seems that that setting doesn't allow us to merge your branch with master. @VinayaSathyanarayana Could you please merge your branch, which should trigger CI, at which point we'll be able to merge your change in.

Sorry for all the fiddling around while we shake down our process for accepting community contributions, we really appreciate your patience and willingness to help out.

**Comment by jesstelford** [comment]
I've created a new branch so we can get it past CI: https://github.com/keystonejs/keystone-5/pull/985

**Pull request closed without merging**
