### PR TITLE
remark validate links

### PR DESCRIPTION
**Pull request by BarryThePenguin**
This PR introduces [`remark-validate-links`](https://github.com/remarkjs/remark-validate-links) to verify links and images references exist in documents.

The attached example points out the links on the [Access Control docs](https://v5.keystonejs.com/api/access-control) are incorrect. Along with another 20 issues

This would require #1059 be merged first as this includes the same commits.

For a clearer comparison see https://github.com/BarryThePenguin/keystone-5/compare/remark-toc...remark-validate-links

Example output...

```
docs/api/README.md: written
docs/api/access-control.md
       11:9-11:63  warning  Link to unknown file: `guides/access-control.md`                                                                     missing-file             remark-validate-links
       12:1-12:55  warning  Link to unknown file: `guides/authentication.md`                                                                     missing-file             remark-validate-links
    627:20-627:71  warning  Link to unknown heading: `admin-ui-display-forms`. Did you mean `admin-ui-display--forms`                            missing-heading          remark-validate-links

docs/api/hooks.md
         9:2-9:35  warning  Link to unknown file: `docs/hooks`                                                                                   missing-file             remark-validate-links
         9:2-9:35  warning  Link to unknown heading in `docs/hooks`: `list-hooks`                                                                missing-heading-in-file  remark-validate-links
        9:37-9:72  warning  Link to unknown file: `docs/hooks`                                                                                   missing-file             remark-validate-links
        9:37-9:72  warning  Link to unknown heading in `docs/hooks`: `field-hooks`                                                               missing-heading-in-file  remark-validate-links
       9:74-10:34  warning  Link to unknown file: `docs/hooks`                                                                                   missing-file             remark-validate-links
       9:74-10:34  warning  Link to unknown heading in `docs/hooks`: `field-type-hooks`                                                          missing-heading-in-file  remark-validate-links
    157:33-158:42  warning  Link to unknown file: `docs/hooks.md`                                                                                missing-file             remark-validate-links
    157:33-158:42  warning  Link to unknown heading in `docs/hooks.md`: `hook-excecution-order`                                                  missing-heading-in-file  remark-validate-links
```

### CODE REVIEW

**Comment by JedWatson** [comment]
Related: #892 (may close that issue?)

**Comment by BarryThePenguin** [comment]
> Related: #892 (may close that issue?)

Yeah, this would solve that issue.

The only thing this wouldn't handle is references to anything outside this git repo

**Comment by timleslie** [comment]
Hi @BarryThePenguin, this looks super useful! As part of this PR could I get you to also update the circle CI config to run this linter and fix the existing issues. If you have any trouble with any of them feel free to shout out and we can help work out where they should be point.

**Comment by BarryThePenguin** [comment]
Good to know, thanks!

I've added linter to CI, you should be able to see all the reported issues. I'll have a look at what I can fix

**Comment by BarryThePenguin** [comment]
The main confusion is around files that do or don't exist in api, discussions, or guides.

eg `/api/access-control` refers to `/guides/access-control.md` and `/guides/authentication.md`, neither which exist. But there is a `/discussion/access-control.md` and a `/discussion/authentication.md`.

There's only one `/authentication.md`, so I'm guessing every reference should point to that?

**Comment by timleslie** [comment]
Yep, if there's only one version of a particular file name but it appears to be in the wrong place then it's probably the case that it was moved from one directory to another at one point but the links weren't updated, so feel free to work on that assumption.

**Comment by BarryThePenguin** [comment]
These are the ones I'm unsure about

- `hooks.md` exists in `api/hooks.md` and `discussions/hooks.md`
- `access-control.md` exists in `api/access-control.md` and `discussions/access-control.md`
- `packages/arch/packages/alert/README.md` links to files that don't exist
- `packages/arch/packages/example.md` has links that no longer exist

```
docs/discussions/access-control.md
    116:18-116:75  warning  Link to unknown file: `guides/access-control.md`                                                                     missing-file             remark-validate-links

docs/discussions/lists.md
      35:48-35:86  warning  Link to unknown file: `docs/access-control.md`. Did you mean `docs/api/access-control.md`                            missing-file             remark-validate-links

docs/discussions/mutation-lifecycle.md
      64:19-64:57  warning  Link to unknown file: `docs/access-control.md`. Did you mean `docs/api/access-control.md`                            missing-file             remark-validate-links
     64:76-64:102  warning  Link to unknown file: `docs/hooks.md`                                                                                missing-file             remark-validate-links
   105:74-105:126  warning  Link to unknown file: `docs/access-control.md`. Did you mean `docs/api/access-control.md`                            missing-file             remark-validate-links

docs/discussions/performance.md
       37:1-37:39  warning  Link to unknown file: `docs/access-control.md`. Did you mean `docs/api/access-control.md`                            missing-file             remark-validate-links

packages/access-control/README.md
      9:106-9:160  warning  Link to unknown file: `guides/access-control.md`                                                                     missing-file             remark-validate-links

packages/arch/packages/alert/README.md
      39:32-39:55  warning  Link to unknown file: `packages/arch/packages/alert/theme`. Did you mean `packages/arch/packages/alert/README.md`    missing-file             remark-validate-links
     145:1-145:17  warning  Link to unknown file: `packages/arch/packages/alert/LICENSE`. Did you mean `packages/arch/packages/alert/README.md`  missing-file             remark-validate-links

packages/arch/packages/example.md
      76:20-76:73  warning  Link to unknown file: `packages/arch/packages/docs/lists-and-keys.html`                                              missing-file             remark-validate-links
      76:20-76:73  warning  Link to unknown heading in `packages/arch/packages/docs/lists-and-keys.html`: `keys`                                 missing-heading-in-file  remark-validate-links
  177:188-177:223  warning  Link to unknown heading: `getting-started`                                                                           missing-heading          remark-validate-links
  239:121-239:154  warning  Link to unknown heading: `getting-started`                                                                           missing-heading          remark-validate-links
```

**Comment by timleslie** [comment]
> ```
> docs/discussions/access-control.md
>     116:18-116:75  warning  Link to unknown file: `guides/access-control.md`                                                                     missing-file             remark-validate-links
> ```

Should be `api/access-control.md`

> ```
> 
> docs/discussions/lists.md
>       35:48-35:86  warning  Link to unknown file: `docs/access-control.md`. Did you mean `docs/api/access-control.md`                            missing-file             remark-validate-links
> ```

Should be `./access-control.md`.

> ```
> 
> docs/discussions/mutation-lifecycle.md
>       64:19-64:57  warning  Link to unknown file: `docs/access-control.md`. Did you mean `docs/api/access-control.md`                            missing-file             remark-validate-links
>      64:76-64:102  warning  Link to unknown file: `docs/hooks.md`                                                                                missing-file             remark-validate-links
>    105:74-105:126  warning  Link to unknown file: `docs/access-control.md`. Did you mean `docs/api/access-control.md`                            missing-file             remark-validate-links

Should be `./access-control.md` and `hooks.md`.

> ```
> 
> docs/discussions/performance.md
>        37:1-37:39  warning  Link to unknown file: `docs/access-control.md`. Did you mean `docs/api/access-control.md`                            missing-file             remark-validate-links
> ```

Should be `./access-control.md`.

> ```
> 
> packages/access-control/README.md
>       9:106-9:160  warning  Link to unknown file: `guides/access-control.md`                                                                     missing-file             remark-validate-links
> ```
Should be `../../discussions/access-control.md`

> ```
> 
> packages/arch/packages/alert/README.md
>       39:32-39:55  warning  Link to unknown file: `packages/arch/packages/alert/theme`. Did you mean `packages/arch/packages/alert/README.md`    missing-file             remark-validate-links
>      145:1-145:17  warning  Link to unknown file: `packages/arch/packages/alert/LICENSE`. Did you mean `packages/arch/packages/alert/README.md`  missing-file             remark-validate-links
> ```

We can just remove both these links I think and leave the raw text.

> ```
> 
> packages/arch/packages/example.md
>       76:20-76:73  warning  Link to unknown file: `packages/arch/packages/docs/lists-and-keys.html`                                              missing-file             remark-validate-links
>       76:20-76:73  warning  Link to unknown heading in `packages/arch/packages/docs/lists-and-keys.html`: `keys`                                 missing-heading-in-file  remark-validate-links
>   177:188-177:223  warning  Link to unknown heading: `getting-started`                                                                           missing-heading          remark-validate-links
>   239:121-239:154  warning  Link to unknown heading: `getting-started`                                                                           missing-heading          remark-validate-links
> ```

We can also simply remove these links as well.

**Comment by BarryThePenguin** [comment]
Thanks @timleslie, that was helpful. The markdown link validation should be 🍏 now

**Pull request merged**
